###

POST http://localhost:4004/documents/sendPayload
Content-Type: application/json 

{
    "to" : "ranjith13119@zngdb.onmicrosoft.com", 
    "Subject" : "test mail from CF"
}

###
GET http://localhost:4004/documents/getDocument()